### ISSUE TITLE
Lege vertalingen worden niet geaccepteerd

### ISSUE THREAD

**Issue by moiristo** [bookingexperts/translator#4]
Gengo accepteert geen jobs waarvoor de content leeg is. In BE hebben we een aantal keys die leeg zijn, bijv:

```yaml
en:
  front_office:
    javascript:
      reservation_reviews:
        hints:
          question_1: ''
```

De submit naar Gengo faalt hierop. We moeten lege keys dus altijd filteren bij een submit. Vervolgens zouden deze wel handmatig toegevoegd moeten kunnen worden (via `export_keys` en `import_keys` bijv.)
